### ISSUE TITLE
STM32F769I-DISC1 QSPI_AutoPollingMemReady fails

### ISSUE THREAD

**Issue by STUBA-rupr** [vlcekji2/External-Loaders#1]
Hi,
first of all, I like the job you done.
Unfortunately, for me it does not work. I followed steps you described, I double checked it with the manual.
I have a question about QSPI_AutoPollingMemReady function.
```
sConfig.Match = 0x8080;
sConfig.Mask = 0x8080;
```
why 0x8080? 
For me works only 
```
sConfig.Match           = 0x00;
sConfig.Mask            = 0x01;  // #define MX25L512_SR_WIP   ((uint8_t)0x01)
```

I guess it has something with the fact, that once I am not debugging step by step 
```
for (var = 0; var < SECTORS_COUNT; var++) {

  		if (CSP_QSPI_EraseSector(var * MEMORY_SECTOR_SIZE,
  				(var + 1) * MEMORY_SECTOR_SIZE - 1) != HAL_OK) {

  			while (1)
  				;  //breakpoint - error detected
  		}

  		if (CSP_QSPI_WriteMemory(buffer_test, var * MEMORY_SECTOR_SIZE,
  				sizeof(buffer_test)) != HAL_OK) {

  			while (1)
  				;  //breakpoint - error detected
  		}

  	}
```
I have nothing in the memory.

**Comment by vlcekji2** [comment]
Hi Rudolf,

you are right. There is an issue in the driver. I have attached complete
example for F769 disco board. Hope it will help you to make it running.

BR,
Jiri

pá 28. 8. 2020 v 16:40 odesílatel Ing. Rudolf Pribis <
notifications@github.com> napsal:

**Comment by STUBA-rupr** [comment]
Šlape to ako hodinky! (Works like a charm!)
thanks a lot!

**Comment by JVLSTM** [comment]
Já díky! Thank you for reporting this bug. Now it should be OK in MX25L512 driver.

**Comment by vlcekji2** [comment]
Já díky! - Thank you for reporting this bug. Now it should be OK in
MX25L512 driver.

po 31. 8. 2020 v 11:57 odesílatel Ing. Rudolf Pribis <
notifications@github.com> napsal:
