### ISSUE TITLE
File .stldr is not accepted by CubeProgrammer or STLink Utility

### ISSUE THREAD

**Issue by STUBA-rupr** [vlcekji2/External-Loaders#2]
Hello @vlcekji2 ,
I created the external loader file following instructions.
It  does not appear in CubeProgrammer and if I try it in ST-Link Utility it takes the one above:
![image](https://user-images.githubusercontent.com/55546830/91733306-a779d000-eba9-11ea-9cd6-599d05b4a1f3.png)
In document [UM0892 User manual STM32 ST-LINK utility software description](https://www.st.com/resource/en/user_manual/cd00262073-stm32-stlink-utility-software-description-stmicroelectronics.pdf) (pp. 31-33) a developing customized loaders for external memory is described.
The function definition *Verify* differs from the one defined in your project.
```
uint64_t Verify (uint32_t FlashAddr, uint32_t RAMBufferAddr, uint32_t Size)
vs.
uint64_t Verify(uint32_t MemoryAddr, uint32_t RAMBufferAddr, uint32_t Size,uint32_t missalignement) // yours
```
Another think I saw is 
```
struct StorageInfo const StorageInfo = {
#endif
"External_Loader_Name", // Device Name + version number
MCU_FLASH, // Device Type
0x08000000, // Device Start Address
0x00100000, // Device Size in Bytes (1MBytes/8Mbits)
0x00004000, // Programming Page Size 16KBytes
0xFF, // Initial Content of Erased Memory
// Specify Size and Address of Sectors (view example below)
0x00000004, 0x00004000, // Sector Num : 4 ,Sector Size: 16KBytes
0x00000001, 0x00010000, // Sector Num : 1 ,Sector Size: 64KBytes
0x00000007, 0x00020000, // Sector Num : 7 ,Sector Size: 128KBytes
0x00000000, 0x00000000,
};
vs.
#else
struct StorageInfo const StorageInfo = {
#endif
		"0QSPI_flashloader_CSP", 	 	         // Device Name + version number
		NOR_FLASH,                  		 // Device Type
		0x90000000,                			 // Device Start Address
		MX25L512_FLASH_SIZE,                 	 // Device Size in Bytes
		MX25L512_PAGE_SIZE,                    // Programming Page Size
		0xFF,                                // Initial Content of Erased Memory

		// Specify Size and Address of Sectors (view example below)
		{ { (MX25L512_FLASH_SIZE / MX25L512_SECTOR_SIZE),  // Sector Numbers,
				(uint32_t) MX25L512_SECTOR_SIZE },       //Sector Size

				{ 0x00000000, 0x00000000 } } };
// note: I took values from memory definition file. The sector size is 0x10000, not 0x1000.
```

The last observation I found is command SECTOR_ERASE_CMD. In mx25l512.h it is defined as 0xD8, while in your quadspi.h it is 0x20, what is according  mx25l512 definition SUBSECTOR_ERASE_CMD.

And could you please explain the *linker.ld* file?
Why RAM start is shifted?
```
MEMORY
{
RAM (xrw)      : ORIGIN = 0x20000004, LENGTH = 512K
}

.isr_vector :
  {
  	. = . + 0x1FC;
    . = ALIGN(4);
    KEEP(*(.isr_vector)) /* Startup code */
    . = ALIGN(4);
  } >RAM :Loader
```

Could you please help me with these points?

**Comment by vlcekji2** [comment]
Hello,

1. Definitely, the loader should appear in CubeProgrammer. Did you un-check
"Discard unused section" in project properties? Anyway, It was already set
in the project I sent you.

2. Verify function should work also with additional parameter (tested on
our side).

3. Both StorageInfo structures contain the same information. There is only
one additional formula which compute sector number automatically from
memory definition:

// Specify Size and Address of Sectors (view example below)
{ { (MEMORY_FLASH_SIZE / MEMORY_SECTOR_SIZE),  // Sector Numbers,
(uint32_t) MEMORY_SECTOR_SIZE },               //Sector Size

4. I am not sure what mx25l512.h you mean but quadspi.h contains values
which correspond with MX25L515 datasheet.
Sector size is 0x1000 and erase sector command is 0x20. You can have a look
to attached datasheet.

Best Regards,
Jiri

po 31. 8. 2020 v 16:58 odesílatel Ing. Rudolf Pribis <
notifications@github.com> napsal:

**Comment by vlcekji2** [comment]
RAM start is shifted because first address of RAM is used for Break instruction. The flashloader is loaded in RAM with Offset 0x4 because at offset 0x0 we write the BKPT instruction which will be executed after any flash loader function to halt the core.
The BKPT address is put in the LR register before running executing any flashloader function (Write, SectorErase,...).

**Comment by STUBA-rupr** [comment]
Hi @vlcekji2 ,
Thanks for clarification. I managed to make it visible in both (Cube Programmer, ST-LINK).
I am more OOP programmer, so this lets say lower programming makes lot of confusions to me.

**Comment by vlcekji2** [comment]
Hi Rudolf,

No problem, I fully understand...just for information: What was the issue?
Was it really un-checking "Discard unused section"? I am curious :-)

Thank you,
Jiri

st 2. 9. 2020 v 15:53 odesílatel Ing. Rudolf Pribis <
notifications@github.com> napsal:

**Comment by STUBA-rupr** [comment]
Honestly, I do not know. About setting "Discard unused section" I am almost sure, that I unchecked it.
I then took functions from Loader_Src.c from ST-LINK example for STM32F769I. I use commands in EN4B mode. If you like I can make the repository public.
Anyway, now I have another issue. As usual.  When I am calling GPIOToggle() from external memory, I have the HardFault_Handler

![image](https://user-images.githubusercontent.com/55546830/92117710-d6848180-edf5-11ea-9e82-a3c413b61ae8.png)

```
#include "extmemFunc.h"
#include "gpio.h"
#include "stm32f7xx_hal.h"


 void __attribute__((section(".extmemFunc"))) GpioToggle(void)
{
	const uint8_t data[] = {64,64,64,64,64,64,64,64,64};
	// set the pin
	GPIOJ->BSRR = (0U << 13);   //set the 13th bit or PJ13
	while(1)
	{

	}
}
```

from ld file 
```
  .extmemFunc :
  {
  	. = ALIGN(4);
  	  *extmemFunc/*.o (.text .text*)	
  	. = ALIGN(4);
  } > QSPI
```
It seems that GPIOJ is not defined in my memory block.

**Comment by vlcekji2** [comment]
Hello,

Ext loader is not visible in CubeProgrammer in case that linker file is not
correct. The issue could be there. But important is that it works now. :-)

1.
GPIO routine should be programmed in External memory properly.. Did you
test external loader functionality in CubeProgrammer? And additionally, Do
you see external memory programming in the debug console window (CubeIDE)?.

2.
You must enable memory mapped mode in the application just before you call
GpioToggle(). You must not call GpioToggle() if memory mapped mode is not
activated.

Best Regards,
Jiri

čt 3. 9. 2020 v 15:02 odesílatel Ing. Rudolf Pribis <
notifications@github.com> napsal:

**Comment by STUBA-rupr** [comment]
Hi Jiri,
I am using the my external loader in CubeIDE, now it works properly.
The memory details seems to be correct:
![image](https://user-images.githubusercontent.com/55546830/92142582-59b4d000-ee14-11ea-8d55-e588d6c2e33a.png)

When I call GpioToggle() from main.c the function can be reached, but fails on line 
```
GPIOJ->BSRR = (0U << 13);   //set the 13th bit or PJ13
```

Same behavior I got when I move the function definition to main.c as _static_ as it is in QSPI_PreInitConfig example. Definitely I oversaw something.

It seems that GPIOJ in .extmemFunc  sector points to 0xFFFFFFF9.

I will double check the the enabling of memory mapped mode.

**Comment by vlcekji2** [comment]
Hello,

Honestly, the implementation below is not correct because if you want to
change pin state, you have to write "1" value to the BSRR register.

GPIOJ->BSRR = (0U << 13); //set the 13th bit or PJ13

If you want to reset the corresponding bit in ODR - you have to write 1 to
bits Bits 31:16.
If you want to set the corresponding bit in ODR - you have to write 1 to
Bits 15:0.

YOu can have a look at the Reference manual -  GPIOx_BSRR description.

Setting of PJ13 should be like:

GPIOJ->BSRR = (1U << 13);

BR,
Jiri


čt 3. 9. 2020 v 18:43 odesílatel Ing. Rudolf Pribis <
notifications@github.com> napsal:

**Comment by STUBA-rupr** [comment]
Hi Jiri, let's forget about the GPIO...
I have wrong setting for memory mapped mode.
I am little bit frustrated from this QUADSPI :) 
Anyway I finished with configuration which works, so my code stored in external memory works. The settings is following:
```
      sCommand.AddressSize       = QSPI_ADDRESS_32_BITS;
      sCommand.AddressMode       = QSPI_ADDRESS_NONE;
      sCommand.AlternateByteMode = QSPI_ALTERNATE_BYTES_NONE;
      sCommand.AlternateBytesSize= QSPI_ALTERNATE_BYTES_8_BITS;
      sCommand.DataMode          = QSPI_DATA_NONE;
      sCommand.DdrMode           = QSPI_DDR_MODE_DISABLE;
      sCommand.DdrHoldHalfCycle  = QSPI_DDR_HHC_ANALOG_DELAY;
      sCommand.SIOOMode          = QSPI_SIOO_INST_EVERY_CMD;
      sCommand.DummyCycles       = 0;
      
      sCommand.Instruction       = 0xB7; // 4B enabled;
      
      hQSPI.State           = HAL_QSPI_STATE_READY;
      
      HAL_QSPI_Command(&hQSPI, &sCommand, 0x10);
...
sCommand.InstructionMode = QSPI_INSTRUCTION_1_LINE;
sCommand.AddressSize = QSPI_ADDRESS_32_BITS;
sCommand.AlternateByteMode = QSPI_ALTERNATE_BYTES_NONE;
sCommand.AddressMode = QSPI_ADDRESS_4_LINES;
sCommand.DdrMode = QSPI_DDR_MODE_DISABLE;
sCommand.SIOOMode = QSPI_SIOO_INST_EVERY_CMD;
sCommand.DataMode = QSPI_DATA_4_LINES;
sCommand.NbData = 0;
sCommand.Address = 0;

sCommand.Instruction = 0xEC; //4READ
sCommand.DummyCycles = 6;
/*
if (HAL_QSPI_Command(&hQSPI, &sCommand, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
{
return 0;
}
*/
// memory mapped mode
sMemMappedCfg.TimeOutActivation = QSPI_TIMEOUT_COUNTER_DISABLE;
sMemMappedCfg.TimeOutPeriod = 0;

if (HAL_QSPI_MemoryMapped(&hQSPI, &sCommand, &sMemMappedCfg) != HAL_OK)
{
return 0;
}
``` 

unfortunately in 4Byte mode I cannot make working the page programming. But for that I can use external loader for MX25L512.
